// Code generated by "stringer -type=EventType -trimprefix=EventType -output=eventType_string.go"; DO NOT EDIT.

package bascule

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EventTypeSuccess-0]
	_ = x[EventTypeMissingCredentials-1]
	_ = x[EventTypeInvalidCredentials-2]
	_ = x[EventTypeFailedAuthentication-3]
	_ = x[EventTypeFailedAuthorization-4]
}

const _EventType_name = "SuccessMissingCredentialsInvalidCredentialsFailedAuthenticationFailedAuthorization"

var _EventType_index = [...]uint8{0, 7, 25, 43, 63, 82}

func (i EventType) String() string {
	if i < 0 || i >= EventType(len(_EventType_index)-1) {
		return "EventType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
