version = 1
SPDX-PackageName = "bascule"
SPDX-PackageSupplier = "Comcast Cable Communications Management, LLC"
SPDX-PackageDownloadLocation = "https://github.com/xmidt-org/bascule"

[[annotations]]
path = "AUTHORS"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "CONTRIBUTING.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".golangci.yaml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "go.mod"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "go.sum"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "NOTICE"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "CHANGELOG.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "MAINTAINERS.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "README.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".whitesource"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "eventType_string.go"
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"
