// Code generated by "stringer -type=ErrorResponseReason"; DO NOT EDIT.

package basculehttp

import "strconv"

const _ErrorResponseReason_name = "MissingHeaderInvalidHeaderKeyNotSupportedParseFailedMissingAuthenticationChecksNotFoundChecksFailed"

var _ErrorResponseReason_index = [...]uint8{0, 13, 26, 41, 52, 73, 87, 99}

func (i ErrorResponseReason) String() string {
	if i < 0 || i >= ErrorResponseReason(len(_ErrorResponseReason_index)-1) {
		return "ErrorResponseReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorResponseReason_name[_ErrorResponseReason_index[i]:_ErrorResponseReason_index[i+1]]
}
