// Code generated by "stringer -type=NotFoundBehavior"; DO NOT EDIT.

package basculehttp

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Forbid-0]
	_ = x[Allow-1]
}

const _NotFoundBehavior_name = "ForbidAllow"

var _NotFoundBehavior_index = [...]uint8{0, 6, 11}

func (i NotFoundBehavior) String() string {
	if i < 0 || i >= NotFoundBehavior(len(_NotFoundBehavior_index)-1) {
		return "NotFoundBehavior(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NotFoundBehavior_name[_NotFoundBehavior_index[i]:_NotFoundBehavior_index[i+1]]
}
