# SPDX-FileCopyrightText: 2024 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: Auto Releaser

on:
  schedule:
    - cron: '0 12 * * *'  # Daily at 12:00 UTC
  workflow_dispatch:

permissions: {}

jobs:
  release:
    uses: xmidt-org/shared-go/.github/workflows/auto-releaser.yml@8f72b028f3bbb741244c9fde8633ecb5ceb77fd0 # main
    secrets: inherit
